const CONFIG = {
    introTitle: 'Babe à!',
    introDesc: 'Trên thế giới có hơn 7 tỷ nụ cười nhưng mà với anh nụ cười em mới là đẹp nhất'
               'Thế nên là làm ơn hãy để anh giúp em giữ nụ cười của em trên môi',
    btnIntro: 'hihi',
    title: 'Hey girl 😙',
    desc: 'anh đã trằn trọc suốt đêm qua đặt ra một câu hỏi tại sao tên em không phải là MẪN NHI. Em có thắc mắc về điều đó không ♥ ',
    btnYes: 'Whyyyyyyy <33',
    btnNo: 'Hông quan tâm :3',
    question:'Bởi vì em chính là MĨ NHÂN của cuộc đời anh <3',
    btnReply: 'Em àaaa <3',
    reply: 'rái đất vốn lạ thường ',
           'Mà sao em cứ đi nhầm đường',
           'Lạc vào tim anh lẻ loi',
           ' Đằng sau chữ yêu đây là thương 🥰🥰🥰',
    mess: 'Quỷ hàaaaaaaaaa😘😘',
    messDesc: 'Cuộc sống anh là của em.',
    btnAccept: 'Hihihihi <3',
    messLink: 'https://www.facebook.com/profile.php?id=100025228957958',
}
